baseURL = "https://matheusrodrisantos.github.io/"
languageCode = "pt-br"
title = "Matheus Rodrigues"
theme = "hugo-blog-awesome"
enableRobotsTXT = true

defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true


[languages]

  [languages.pt]
    languageName = "Português"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2

    
[pagination]
  pagerSize = 10

[params]
  description = "Artigos sobre tecnologia, Linux e desenvolvimento"
  mainSections = ["posts"]
  dateFormat = "02/01/2006"
  hideReadingTime = false
  readingTimeText = "min de leitura"
  defaultTheme = "auto"

  # Links de contato
  github = "https://github.com/matheusrodrisantos"
  linkedin = "https://www.linkedin.com/in/matheus-rodrigues-888980119/"
  showAvatarInNavbar = true
  showAuthorAvatar = true


[params.author]
  name = "Matheus Rodrigues"
  bio = "Desenvolvedor e entusiasta de Linux, DevOps e open source."
  avatar = "/images/avatar.jpeg"

[menu]

  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 3

  [[menu.main]]
    name = "Projetos"
    url = "/projetos/"
    weight = 4